name: Python Compilation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install openai

    - name: Compile Python files
      run: |
        set -e
        for file in $(find . -name '*.py'); do
          python -m py_compile $file || true
        done

    - name: Check for errors
      run: |
        set -e
        if grep -Rl '^SyntaxError' .; then
          echo "There are syntax errors in some Python files."
          exit 1
        fi

    - name: Ignore Warnings
      run: |
        set -e
        echo "All Python files compiled successfully without errors."
